
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaceDeUso;

import corpoPrograma.Principal;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 */
public class PaginaInicial extends javax.swing.JFrame {

    /**
     * Creates new form PaginaInicial
     */
    public PaginaInicial() {
        initComponents();
        controle = new Principal(painelPrincipal); // É preciso passar o painel no construtor por causa da verificação da senha
        controle.carregarVagasTabela(TableFiltro);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        painelPrincipal = new javax.swing.JPanel();
        paginaPrincipal = new javax.swing.JPanel();
        TitlePag = new javax.swing.JLabel();
        AdcScroll = new javax.swing.JScrollPane();
        TodasVagas = new javax.swing.JTextArea();
        BotaoAluno = new javax.swing.JButton();
        BotaoAdm = new javax.swing.JButton();
        BotaoSair = new javax.swing.JButton();
        IntrPrinc = new javax.swing.JLabel();
        IDPrinc = new javax.swing.JTextField();
        VisualVg = new javax.swing.JButton();
        paginaFiltro = new javax.swing.JPanel();
        BotaoLupa = new javax.swing.JButton();
        SlcArea = new javax.swing.JComboBox<>();
        SlcHora = new javax.swing.JComboBox<>();
        SlcValor = new javax.swing.JComboBox<>();
        BotaoVoltar = new javax.swing.JButton();
        TitleFiltro = new javax.swing.JLabel();
        IntrFiltro = new javax.swing.JLabel();
        IDFiltro = new javax.swing.JTextField();
        VisualFiltro = new javax.swing.JButton();
        ScrollTable = new javax.swing.JScrollPane();
        TableFiltro = new javax.swing.JTable();
        labelAreaFiltro = new javax.swing.JLabel();
        labelTurnoFiltro = new javax.swing.JLabel();
        labelSalFiltro = new javax.swing.JLabel();
        paginaAdm = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        BotaoAdc = new javax.swing.JButton();
        BotaoEditar = new javax.swing.JButton();
        BotaoRmv = new javax.swing.JButton();
        BotaoVoltarAdm = new javax.swing.JButton();
        TitleAdm = new javax.swing.JLabel();
        paginaAdc = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TitleAdc = new javax.swing.JLabel();
        TitleNome = new javax.swing.JLabel();
        NomeVg = new javax.swing.JTextField();
        TitleArea = new javax.swing.JLabel();
        AreaCad = new javax.swing.JComboBox<>();
        TitleSal = new javax.swing.JLabel();
        SalarioCad = new javax.swing.JTextField();
        TitleHora = new javax.swing.JLabel();
        HorarioCad = new javax.swing.JComboBox<>();
        BotaoCancel = new javax.swing.JButton();
        BotaoCadastra = new javax.swing.JButton();
        TitleEmpresa = new javax.swing.JLabel();
        NomeEmpresa = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TexCad = new javax.swing.JTextArea();
        paginaRemove = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        BotaoLupaRmv = new javax.swing.JButton();
        SlcAreaRmv = new javax.swing.JComboBox<>();
        SlcHoraRmv = new javax.swing.JComboBox<>();
        SlcValorRmv = new javax.swing.JComboBox<>();
        TitleRmv = new javax.swing.JLabel();
        IntrRmv = new javax.swing.JLabel();
        IDRmv = new javax.swing.JTextField();
        RemoveVg = new javax.swing.JButton();
        BotaoVoltarRmv = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TableRmv = new javax.swing.JTable();
        labelAreaRmv = new javax.swing.JLabel();
        labelTurnoRvm = new javax.swing.JLabel();
        labelSalRmv = new javax.swing.JLabel();
        paginaEdit = new javax.swing.JPanel();
        SlcAreaEdit = new javax.swing.JComboBox<>();
        SlcHoraEdit = new javax.swing.JComboBox<>();
        SlcValorEdit = new javax.swing.JComboBox<>();
        TitleEdit = new javax.swing.JLabel();
        IntrEdit = new javax.swing.JLabel();
        IDEdit = new javax.swing.JTextField();
        EditVg = new javax.swing.JButton();
        BotaoVoltarEdit = new javax.swing.JButton();
        BotaoLupaEdit = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TableEdit = new javax.swing.JTable();
        labelAreaEdt = new javax.swing.JLabel();
        labelTurnoEdt = new javax.swing.JLabel();
        labelSalEdt = new javax.swing.JLabel();
        paginaVagaPesquisada = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        nomeVg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        empresaVg = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        areaVg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        turnoVg = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        salarioVg = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        descricaoVg = new javax.swing.JTextArea();
        BotaoVoltarVg = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelPrincipal.setLayout(new java.awt.CardLayout());

        paginaPrincipal.setBackground(new java.awt.Color(255, 228, 196));
        paginaPrincipal.setPreferredSize(new java.awt.Dimension(700, 600));

        TitlePag.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TitlePag.setText("Bem vindo ao VagasExpress!");

        AdcScroll.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        TodasVagas.setEditable(false);
        TodasVagas.setColumns(20);
        TodasVagas.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TodasVagas.setRows(5);
        AdcScroll.setViewportView(TodasVagas);

        BotaoAluno.setBackground(new java.awt.Color(46, 139, 87));
        BotaoAluno.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoAluno.setText("Aluno");
        BotaoAluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAlunoActionPerformed(evt);
            }
        });

        BotaoAdm.setBackground(new java.awt.Color(46, 139, 87));
        BotaoAdm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoAdm.setText("Administrar");
        BotaoAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAdmActionPerformed(evt);
            }
        });

        BotaoSair.setBackground(new java.awt.Color(255, 0, 0));
        BotaoSair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoSair.setText("Sair");
        BotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairActionPerformed(evt);
            }
        });

        IntrPrinc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IntrPrinc.setText("Digite o ID da vaga:");

        VisualVg.setBackground(new java.awt.Color(60, 179, 113));
        VisualVg.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Área de Trabalho\\Docs_2_Semestre\\loupe.png")); // NOI18N

        javax.swing.GroupLayout paginaPrincipalLayout = new javax.swing.GroupLayout(paginaPrincipal);
        paginaPrincipal.setLayout(paginaPrincipalLayout);
        paginaPrincipalLayout.setHorizontalGroup(
            paginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaPrincipalLayout.createSequentialGroup()
                .addGroup(paginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paginaPrincipalLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(paginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TitlePag)
                            .addComponent(AdcScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paginaPrincipalLayout.createSequentialGroup()
                                .addComponent(IntrPrinc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IDPrinc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VisualVg, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(paginaPrincipalLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(BotaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(paginaPrincipalLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(BotaoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        paginaPrincipalLayout.setVerticalGroup(
            paginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitlePag)
                .addGap(18, 18, 18)
                .addComponent(AdcScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(paginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(VisualVg, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(paginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IntrPrinc)
                        .addComponent(IDPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoAluno, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(BotaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        painelPrincipal.add(paginaPrincipal, "card2");

        paginaFiltro.setBackground(new java.awt.Color(255, 228, 196));
        paginaFiltro.setPreferredSize(new java.awt.Dimension(700, 600));

        BotaoLupa.setBackground(new java.awt.Color(60, 179, 113));
        BotaoLupa.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Área de Trabalho\\Docs_2_Semestre\\loupe.png")); // NOI18N
        BotaoLupa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLupaActionPerformed(evt);
            }
        });

        SlcArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Computação", "Direito", "Administração", "Mecânica" }));
        SlcArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlcAreaActionPerformed(evt);
            }
        });

        SlcHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Manhã", "Tarde", "Noite" }));
        SlcHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlcHoraActionPerformed(evt);
            }
        });

        SlcValor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "500-1000", "1000-1500", "1500-2000", "2000 +" }));
        SlcValor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlcValorActionPerformed(evt);
            }
        });

        BotaoVoltar.setBackground(new java.awt.Color(176, 224, 230));
        BotaoVoltar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoVoltar.setText("Voltar");
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });

        TitleFiltro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TitleFiltro.setText("Filtre entre as vagas disponíveis:");

        IntrFiltro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IntrFiltro.setText("Digite o ID da vaga:");

        VisualFiltro.setBackground(new java.awt.Color(60, 179, 113));
        VisualFiltro.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Área de Trabalho\\Docs_2_Semestre\\search.png")); // NOI18N
        VisualFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VisualFiltroActionPerformed(evt);
            }
        });

        ScrollTable.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        TableFiltro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Empresa", "Área", "Salário (R$)", "Turno"
            }
        ));
        ScrollTable.setViewportView(TableFiltro);

        labelAreaFiltro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelAreaFiltro.setText("Área :");

        labelTurnoFiltro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTurnoFiltro.setText("Turno :");

        labelSalFiltro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelSalFiltro.setText("Salário :");

        javax.swing.GroupLayout paginaFiltroLayout = new javax.swing.GroupLayout(paginaFiltro);
        paginaFiltro.setLayout(paginaFiltroLayout);
        paginaFiltroLayout.setHorizontalGroup(
            paginaFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaFiltroLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(paginaFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TitleFiltro)
                    .addComponent(ScrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(paginaFiltroLayout.createSequentialGroup()
                        .addComponent(BotaoLupa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(paginaFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SlcArea, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAreaFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(paginaFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SlcHora, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTurnoFiltro))
                        .addGap(18, 18, 18)
                        .addGroup(paginaFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SlcValor, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSalFiltro)))
                    .addGroup(paginaFiltroLayout.createSequentialGroup()
                        .addGroup(paginaFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(paginaFiltroLayout.createSequentialGroup()
                                .addComponent(IntrFiltro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IDFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paginaFiltroLayout.createSequentialGroup()
                                .addGap(257, 257, 257)
                                .addComponent(BotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(VisualFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 33, Short.MAX_VALUE))
        );
        paginaFiltroLayout.setVerticalGroup(
            paginaFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaFiltroLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TitleFiltro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paginaFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAreaFiltro)
                    .addComponent(labelTurnoFiltro)
                    .addComponent(labelSalFiltro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paginaFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoLupa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SlcArea, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SlcHora, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SlcValor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ScrollTable, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(paginaFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paginaFiltroLayout.createSequentialGroup()
                        .addGroup(paginaFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IntrFiltro)
                            .addComponent(IDFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(14, 14, 14))
                    .addComponent(VisualFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painelPrincipal.add(paginaFiltro, "card3");

        paginaAdm.setBackground(new java.awt.Color(255, 228, 196));
        paginaAdm.setPreferredSize(new java.awt.Dimension(700, 600));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BotaoAdc.setBackground(new java.awt.Color(46, 139, 87));
        BotaoAdc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoAdc.setText("Adicionar");
        BotaoAdc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAdcActionPerformed(evt);
            }
        });

        BotaoEditar.setBackground(new java.awt.Color(64, 224, 208));
        BotaoEditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoEditar.setText("Editar");
        BotaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEditarActionPerformed(evt);
            }
        });

        BotaoRmv.setBackground(new java.awt.Color(255, 0, 0));
        BotaoRmv.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoRmv.setText("Remover");
        BotaoRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRmvActionPerformed(evt);
            }
        });

        BotaoVoltarAdm.setBackground(new java.awt.Color(176, 224, 230));
        BotaoVoltarAdm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoVoltarAdm.setText("Voltar");
        BotaoVoltarAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarAdmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotaoAdc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoRmv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoVoltarAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(BotaoAdc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(BotaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(BotaoRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(BotaoVoltarAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        TitleAdm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TitleAdm.setText("Bem vindo a central de cadastro!");

        javax.swing.GroupLayout paginaAdmLayout = new javax.swing.GroupLayout(paginaAdm);
        paginaAdm.setLayout(paginaAdmLayout);
        paginaAdmLayout.setHorizontalGroup(
            paginaAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paginaAdmLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(paginaAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TitleAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133))
        );
        paginaAdmLayout.setVerticalGroup(
            paginaAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paginaAdmLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TitleAdm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        painelPrincipal.add(paginaAdm, "card4");

        paginaAdc.setBackground(new java.awt.Color(255, 228, 196));
        paginaAdc.setPreferredSize(new java.awt.Dimension(700, 600));

        jPanel2.setBackground(new java.awt.Color(255, 228, 196));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 600));

        TitleAdc.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        TitleAdc.setText("Adicione as informações:");

        TitleNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TitleNome.setText("Nome :");

        NomeVg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeVgActionPerformed(evt);
            }
        });

        TitleArea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TitleArea.setText("Area :");

        AreaCad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computação", "Direito", "Administração", "Mecânica" }));
        AreaCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaCadActionPerformed(evt);
            }
        });

        TitleSal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TitleSal.setText("Salario :");

        SalarioCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalarioCadActionPerformed(evt);
            }
        });

        TitleHora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TitleHora.setText("Horário :");

        HorarioCad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manhã", "Tarde", "Noite" }));

        BotaoCancel.setBackground(new java.awt.Color(255, 0, 0));
        BotaoCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotaoCancel.setText("Cancelar");
        BotaoCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelActionPerformed(evt);
            }
        });

        BotaoCadastra.setBackground(new java.awt.Color(60, 179, 113));
        BotaoCadastra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotaoCadastra.setText("Cadastrar");
        BotaoCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastraActionPerformed(evt);
            }
        });

        TitleEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TitleEmpresa.setText("Empresa :");

        NomeEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeEmpresaActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Descrição :");

        TexCad.setColumns(20);
        TexCad.setRows(5);
        jScrollPane4.setViewportView(TexCad);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(270, 270, 270)
                .addComponent(TitleAdc)
                .addContainerGap(240, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 180, Short.MAX_VALUE)
                .addComponent(BotaoCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100)
                .addComponent(BotaoCadastra, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(180, 180, 180))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TitleSal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SalarioCad, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TitleNome)
                            .addComponent(TitleArea))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(NomeVg)
                            .addComponent(AreaCad, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TitleEmpresa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(NomeEmpresa))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(TitleHora)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(HorarioCad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(120, 120, 120))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleAdc)
                .addGap(53, 53, 53)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleNome)
                    .addComponent(NomeVg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleEmpresa)
                    .addComponent(NomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleArea)
                    .addComponent(AreaCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleSal)
                    .addComponent(SalarioCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleHora)
                    .addComponent(HorarioCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoCadastra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout paginaAdcLayout = new javax.swing.GroupLayout(paginaAdc);
        paginaAdc.setLayout(paginaAdcLayout);
        paginaAdcLayout.setHorizontalGroup(
            paginaAdcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaAdcLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        paginaAdcLayout.setVerticalGroup(
            paginaAdcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaAdcLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        painelPrincipal.add(paginaAdc, "card5");

        paginaRemove.setPreferredSize(new java.awt.Dimension(700, 600));

        jPanel3.setBackground(new java.awt.Color(255, 228, 196));

        BotaoLupaRmv.setBackground(new java.awt.Color(60, 179, 113));
        BotaoLupaRmv.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Área de Trabalho\\Docs_2_Semestre\\loupe.png")); // NOI18N
        BotaoLupaRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLupaRmvActionPerformed(evt);
            }
        });

        SlcAreaRmv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Computação", "Direito", "Administração", "Mecânica" }));

        SlcHoraRmv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Manhã", "Tarde", "Noite" }));
        SlcHoraRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlcHoraRmvActionPerformed(evt);
            }
        });

        SlcValorRmv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "500-1000", "1000-1500", "1500-2000", "2000 +" }));

        TitleRmv.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TitleRmv.setText("Filtre entre as vagas disponíveis:");

        IntrRmv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IntrRmv.setText("Digite o ID da vaga:");

        RemoveVg.setBackground(new java.awt.Color(255, 0, 0));
        RemoveVg.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Área de Trabalho\\Docs_2_Semestre\\trash-can.png")); // NOI18N
        RemoveVg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveVgActionPerformed(evt);
            }
        });

        BotaoVoltarRmv.setBackground(new java.awt.Color(176, 224, 230));
        BotaoVoltarRmv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotaoVoltarRmv.setText("Voltar");
        BotaoVoltarRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarRmvActionPerformed(evt);
            }
        });

        TableRmv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Empresa", "Área", "Salário (R$)", "Turno"
            }
        ));
        jScrollPane5.setViewportView(TableRmv);

        labelAreaRmv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelAreaRmv.setText("Área :");

        labelTurnoRvm.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTurnoRvm.setText("Turno :");

        labelSalRmv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelSalRmv.setText("Salário :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotaoVoltarRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(257, 257, 257))
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(IntrRmv)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(IDRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(RemoveVg, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(BotaoLupaRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SlcAreaRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelAreaRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SlcHoraRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelTurnoRvm))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(SlcValorRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelSalRmv))))
                    .addComponent(TitleRmv))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TitleRmv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAreaRmv)
                    .addComponent(labelTurnoRvm)
                    .addComponent(labelSalRmv))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoLupaRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SlcAreaRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SlcHoraRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SlcValorRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RemoveVg, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(IntrRmv)
                        .addComponent(IDRmv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoVoltarRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout paginaRemoveLayout = new javax.swing.GroupLayout(paginaRemove);
        paginaRemove.setLayout(paginaRemoveLayout);
        paginaRemoveLayout.setHorizontalGroup(
            paginaRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        paginaRemoveLayout.setVerticalGroup(
            paginaRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        painelPrincipal.add(paginaRemove, "card6");

        paginaEdit.setBackground(new java.awt.Color(255, 228, 196));
        paginaEdit.setPreferredSize(new java.awt.Dimension(700, 600));

        SlcAreaEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Computação", "Direito", "Administração", "Mecânica" }));

        SlcHoraEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "Manhã", "Tarde", "Noite", " " }));
        SlcHoraEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlcHoraEditActionPerformed(evt);
            }
        });

        SlcValorEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Todos", "500-1000", "1000-1500", "1500-2000", "2000 +" }));

        TitleEdit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TitleEdit.setText("Filtre entre as vagas disponíveis:");

        IntrEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IntrEdit.setText("Digite o ID da vaga:");

        EditVg.setBackground(new java.awt.Color(60, 179, 113));
        EditVg.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Área de Trabalho\\Docs_2_Semestre\\pencil.png")); // NOI18N
        EditVg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditVgActionPerformed(evt);
            }
        });

        BotaoVoltarEdit.setBackground(new java.awt.Color(176, 224, 230));
        BotaoVoltarEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotaoVoltarEdit.setText("Voltar");
        BotaoVoltarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarEditActionPerformed(evt);
            }
        });

        BotaoLupaEdit.setBackground(new java.awt.Color(60, 179, 113));
        BotaoLupaEdit.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Área de Trabalho\\Docs_2_Semestre\\loupe.png")); // NOI18N
        BotaoLupaEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoLupaEditActionPerformed(evt);
            }
        });

        TableEdit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "Empresa", "Área", "Salário (R$)", "Turno"
            }
        ));
        jScrollPane3.setViewportView(TableEdit);

        labelAreaEdt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelAreaEdt.setText("Área :");

        labelTurnoEdt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelTurnoEdt.setText("Turno :");

        labelSalEdt.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        labelSalEdt.setText("Salário :");

        javax.swing.GroupLayout paginaEditLayout = new javax.swing.GroupLayout(paginaEdit);
        paginaEdit.setLayout(paginaEditLayout);
        paginaEditLayout.setHorizontalGroup(
            paginaEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaEditLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(paginaEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paginaEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(paginaEditLayout.createSequentialGroup()
                            .addComponent(IntrEdit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(IDEdit)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(EditVg, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paginaEditLayout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(BotaoVoltarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TitleEdit)
                    .addGroup(paginaEditLayout.createSequentialGroup()
                        .addComponent(BotaoLupaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(paginaEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SlcAreaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAreaEdt, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(paginaEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SlcHoraEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTurnoEdt))
                        .addGap(18, 18, 18)
                        .addGroup(paginaEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(SlcValorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelSalEdt))))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        paginaEditLayout.setVerticalGroup(
            paginaEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaEditLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TitleEdit)
                .addGap(7, 7, 7)
                .addGroup(paginaEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelAreaEdt)
                    .addComponent(labelTurnoEdt)
                    .addComponent(labelSalEdt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paginaEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoLupaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SlcAreaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SlcHoraEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SlcValorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(paginaEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IntrEdit)
                    .addComponent(IDEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditVg, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BotaoVoltarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        painelPrincipal.add(paginaEdit, "card7");

        paginaVagaPesquisada.setBackground(new java.awt.Color(255, 228, 196));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Vaga Pesquisada :");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Nome :");

        nomeVg.setEditable(false);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Empresa :");

        empresaVg.setEditable(false);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Área :");

        areaVg.setEditable(false);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Turno :");

        turnoVg.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Salário :");

        salarioVg.setEditable(false);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Descrição :");

        descricaoVg.setEditable(false);
        descricaoVg.setColumns(20);
        descricaoVg.setRows(5);
        jScrollPane6.setViewportView(descricaoVg);

        BotaoVoltarVg.setBackground(new java.awt.Color(176, 224, 230));
        BotaoVoltarVg.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotaoVoltarVg.setText("Voltar");
        BotaoVoltarVg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarVgActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paginaVagaPesquisadaLayout = new javax.swing.GroupLayout(paginaVagaPesquisada);
        paginaVagaPesquisada.setLayout(paginaVagaPesquisadaLayout);
        paginaVagaPesquisadaLayout.setHorizontalGroup(
            paginaVagaPesquisadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaVagaPesquisadaLayout.createSequentialGroup()
                .addGroup(paginaVagaPesquisadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paginaVagaPesquisadaLayout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel2))
                    .addGroup(paginaVagaPesquisadaLayout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(BotaoVoltarVg, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paginaVagaPesquisadaLayout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(paginaVagaPesquisadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(paginaVagaPesquisadaLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(areaVg, javax.swing.GroupLayout.PREFERRED_SIZE, 407, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paginaVagaPesquisadaLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(empresaVg))
                            .addGroup(paginaVagaPesquisadaLayout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeVg, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paginaVagaPesquisadaLayout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(turnoVg))
                            .addGroup(paginaVagaPesquisadaLayout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(salarioVg))
                            .addGroup(paginaVagaPesquisadaLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(125, Short.MAX_VALUE))
        );
        paginaVagaPesquisadaLayout.setVerticalGroup(
            paginaVagaPesquisadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaVagaPesquisadaLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(paginaVagaPesquisadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(nomeVg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paginaVagaPesquisadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(empresaVg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paginaVagaPesquisadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(areaVg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paginaVagaPesquisadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(salarioVg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paginaVagaPesquisadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(turnoVg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paginaVagaPesquisadaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(36, 36, 36)
                .addComponent(BotaoVoltarVg, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17))
        );

        painelPrincipal.add(paginaVagaPesquisada, "card8");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void BotaoAlunoActionPerformed(java.awt.event.ActionEvent evt) {                                           
        CardLayout troca = (CardLayout) painelPrincipal.getLayout(); // Vai da pg Principal para a pg de Filtro
        controle.carregarVagasTabela(TableFiltro);
        troca.show(painelPrincipal, "card3");
    }                                          

    private void BotaoSairActionPerformed(java.awt.event.ActionEvent evt) {                                          
        System.exit(0);
    }                                         

    private void SlcHoraActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        CardLayout troca = (CardLayout) painelPrincipal.getLayout(); // Vai da pg de Filtro para a pg Principal
        troca.show(painelPrincipal, "card2");
    }                                           

    private void BotaoEditarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        CardLayout troca = (CardLayout) painelPrincipal.getLayout();
        controle.carregarVagasTabela(TableEdit);
        troca.show(painelPrincipal, "card7");
    }                                           

    private void BotaoAdcActionPerformed(java.awt.event.ActionEvent evt) {                                         
        CardLayout troca = (CardLayout) painelPrincipal.getLayout();
        troca.show(painelPrincipal, "card5");
    }                                        

    private void BotaoRmvActionPerformed(java.awt.event.ActionEvent evt) {                                         
        CardLayout troca = (CardLayout) painelPrincipal.getLayout();
        controle.carregarVagasTabela(TableRmv);
        troca.show(painelPrincipal, "card6");
    }                                        

    private void BotaoVoltarAdmActionPerformed(java.awt.event.ActionEvent evt) {                                               
        CardLayout troca = (CardLayout) painelPrincipal.getLayout(); // Vai da pg de Adm para a pg Principal
        troca.show(painelPrincipal, "card2");
    }                                              

    private void BotaoAdmActionPerformed(java.awt.event.ActionEvent evt) {                                         
        controle.verificaSenha();
    }                                        

    private void NomeVgActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void AreaCadActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void SalarioCadActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void BotaoCancelActionPerformed(java.awt.event.ActionEvent evt) {                                            
        CardLayout troca = (CardLayout) painelPrincipal.getLayout();
        troca.show(painelPrincipal, "card4");
    }                                           

    private void SlcHoraRmvActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void BotaoVoltarRmvActionPerformed(java.awt.event.ActionEvent evt) {                                               
        CardLayout troca = (CardLayout) painelPrincipal.getLayout();
        troca.show(painelPrincipal, "card4");
    }                                              

    private void SlcHoraEditActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void BotaoVoltarEditActionPerformed(java.awt.event.ActionEvent evt) {                                                
        CardLayout troca = (CardLayout) painelPrincipal.getLayout();
        troca.show(painelPrincipal, "card4");
    }                                               

    private void NomeEmpresaActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void BotaoCadastraActionPerformed(java.awt.event.ActionEvent evt) {                                              
        String nome = NomeVg.getText();
        String empresa = NomeEmpresa.getText();
        String area = (String) AreaCad.getSelectedItem();
        String salario = SalarioCad.getText();
        String horario = (String) HorarioCad.getSelectedItem();
        String descricao = TexCad.getText();
        if (nome.isEmpty() || empresa.isEmpty() || salario.isEmpty() || descricao.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.");
        } else {
            controle.cadastrarVaga(nome, empresa, area, salario, horario, descricao);
            JOptionPane.showMessageDialog(this, "Vaga cadastrada com sucesso!");

            //Limpa os textField após pegar a informação
            NomeVg.setText("");
            NomeEmpresa.setText("");
            SalarioCad.setText("");
            TexCad.setText("");

            CardLayout troca = (CardLayout) painelPrincipal.getLayout();
            troca.show(painelPrincipal, "card4");
        }
    }                                             

    private void RemoveVgActionPerformed(java.awt.event.ActionEvent evt) {                                         
       String Aux = IDRmv.getText();
       controle.removerVagaPesquisada(Aux);
       IDRmv.setText(""); 
       controle.ajustarIDs();
       controle.carregarVagasTabela(TableRmv);
        
// TODO add your handling code here:
    }                                        

    private void VisualFiltroActionPerformed(java.awt.event.ActionEvent evt) {                                             
        CardLayout troca = (CardLayout) painelPrincipal.getLayout();
        String Id = IDFiltro.getText();
        if (Id.equals("")) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha o ID.");
        } else {
            controle.carregaVagaPesquisada(Id, nomeVg, empresaVg, areaVg, salarioVg, turnoVg, descricaoVg);
        }

        troca.show(painelPrincipal, "card8");
    }                                            

    private void BotaoLupaActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // Obter os valores selecionados nos componentes
        String areaSelecionada = SlcArea.getSelectedItem().toString();
        String horarioSelecionado = SlcHora.getSelectedItem().toString();
        String valorSelecionado = SlcValor.getSelectedItem().toString();

        // Chamar a função que carrega os dados filtrados na tabela
        //ATENÇÃO AO ESCREVER APOS MUDANCA NA INTERFACE MUDA O TABLEFILTRO POR TABLEREMOVE
        controle.carregarVagasTabelaFiltrada(TableFiltro, areaSelecionada, horarioSelecionado, valorSelecionado);
    }                                         

    private void BotaoLupaEditActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // Obter os valores selecionados nos componentes
        String areaSelecionadaEdit = SlcAreaEdit.getSelectedItem().toString();
        String horarioSelecionadoEdit = SlcHoraEdit.getSelectedItem().toString();
        String valorSelecionadoEdit = SlcValorEdit.getSelectedItem().toString();

        // Chamar a função que carrega os dados filtrados na tabela
        controle.carregarVagasTabelaFiltrada(TableEdit, areaSelecionadaEdit, horarioSelecionadoEdit, valorSelecionadoEdit);
    }                                             

    private void EditVgActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void SlcValorActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void BotaoLupaRmvActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // Obter os valores selecionados nos componentes
        String areaSelecionadaRmv = SlcAreaRmv.getSelectedItem().toString();
        String horarioSelecionadoRvm = SlcHoraRmv.getSelectedItem().toString();
        String valorSelecionadoRmv = SlcValorRmv.getSelectedItem().toString();

        // Chamar a função que carrega os dados filtrados na tabela
        controle.carregarVagasTabelaFiltrada(TableRmv, areaSelecionadaRmv, horarioSelecionadoRvm, valorSelecionadoRmv);
    }                                            

    private void BotaoVoltarVgActionPerformed(java.awt.event.ActionEvent evt) {                                              
        CardLayout troca = (CardLayout) painelPrincipal.getLayout();
        IDFiltro.setText("");
        troca.show(painelPrincipal, "card3");
    }                                             

    private void SlcAreaActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaInicial().setVisible(true);
            }
        });
    }

    Principal controle;
    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane AdcScroll;
    private javax.swing.JComboBox<String> AreaCad;
    private javax.swing.JButton BotaoAdc;
    private javax.swing.JButton BotaoAdm;
    private javax.swing.JButton BotaoAluno;
    private javax.swing.JButton BotaoCadastra;
    private javax.swing.JButton BotaoCancel;
    private javax.swing.JButton BotaoEditar;
    private javax.swing.JButton BotaoLupa;
    private javax.swing.JButton BotaoLupaEdit;
    private javax.swing.JButton BotaoLupaRmv;
    private javax.swing.JButton BotaoRmv;
    private javax.swing.JButton BotaoSair;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JButton BotaoVoltarAdm;
    private javax.swing.JButton BotaoVoltarEdit;
    private javax.swing.JButton BotaoVoltarRmv;
    private javax.swing.JButton BotaoVoltarVg;
    private javax.swing.JButton EditVg;
    private javax.swing.JComboBox<String> HorarioCad;
    private javax.swing.JTextField IDEdit;
    private javax.swing.JTextField IDFiltro;
    private javax.swing.JTextField IDPrinc;
    private javax.swing.JTextField IDRmv;
    private javax.swing.JLabel IntrEdit;
    private javax.swing.JLabel IntrFiltro;
    private javax.swing.JLabel IntrPrinc;
    private javax.swing.JLabel IntrRmv;
    private javax.swing.JTextField NomeEmpresa;
    private javax.swing.JTextField NomeVg;
    private javax.swing.JButton RemoveVg;
    private javax.swing.JTextField SalarioCad;
    private javax.swing.JScrollPane ScrollTable;
    private javax.swing.JComboBox<String> SlcArea;
    private javax.swing.JComboBox<String> SlcAreaEdit;
    private javax.swing.JComboBox<String> SlcAreaRmv;
    private javax.swing.JComboBox<String> SlcHora;
    private javax.swing.JComboBox<String> SlcHoraEdit;
    private javax.swing.JComboBox<String> SlcHoraRmv;
    private javax.swing.JComboBox<String> SlcValor;
    private javax.swing.JComboBox<String> SlcValorEdit;
    private javax.swing.JComboBox<String> SlcValorRmv;
    private javax.swing.JTable TableEdit;
    private javax.swing.JTable TableFiltro;
    private javax.swing.JTable TableRmv;
    private javax.swing.JTextArea TexCad;
    private javax.swing.JLabel TitleAdc;
    private javax.swing.JLabel TitleAdm;
    private javax.swing.JLabel TitleArea;
    private javax.swing.JLabel TitleEdit;
    private javax.swing.JLabel TitleEmpresa;
    private javax.swing.JLabel TitleFiltro;
    private javax.swing.JLabel TitleHora;
    private javax.swing.JLabel TitleNome;
    private javax.swing.JLabel TitlePag;
    private javax.swing.JLabel TitleRmv;
    private javax.swing.JLabel TitleSal;
    private javax.swing.JTextArea TodasVagas;
    private javax.swing.JButton VisualFiltro;
    private javax.swing.JButton VisualVg;
    private javax.swing.JTextField areaVg;
    private javax.swing.JTextArea descricaoVg;
    private javax.swing.JTextField empresaVg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JLabel labelAreaEdt;
    private javax.swing.JLabel labelAreaFiltro;
    private javax.swing.JLabel labelAreaRmv;
    private javax.swing.JLabel labelSalEdt;
    private javax.swing.JLabel labelSalFiltro;
    private javax.swing.JLabel labelSalRmv;
    private javax.swing.JLabel labelTurnoEdt;
    private javax.swing.JLabel labelTurnoFiltro;
    private javax.swing.JLabel labelTurnoRvm;
    private javax.swing.JTextField nomeVg;
    private javax.swing.JPanel paginaAdc;
    private javax.swing.JPanel paginaAdm;
    private javax.swing.JPanel paginaEdit;
    private javax.swing.JPanel paginaFiltro;
    private javax.swing.JPanel paginaPrincipal;
    private javax.swing.JPanel paginaRemove;
    private javax.swing.JPanel paginaVagaPesquisada;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JTextField salarioVg;
    private javax.swing.JTextField turnoVg;
    // End of variables declaration                   
}
