/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package interfaceDeUso;

import corpoPrograma.Principal;
import java.awt.CardLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author Gabriel
 */
public class PaginaInicial extends javax.swing.JFrame {

    /**
     * Creates new form PaginaInicial
     */
    public PaginaInicial() {
        initComponents();
        controle = new Principal(painelPrincipal); // É preciso passar o painel no construtor por causa da verificação da senha
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        paginaPrincipal = new javax.swing.JPanel();
        TitlePag = new javax.swing.JLabel();
        AdcScroll = new javax.swing.JScrollPane();
        TodasVagas = new javax.swing.JTextArea();
        BotaoFiltro = new javax.swing.JButton();
        BotaoAdm = new javax.swing.JButton();
        BotaoSair = new javax.swing.JButton();
        IntrPrinc = new javax.swing.JLabel();
        IDPrinc = new javax.swing.JTextField();
        VisualVg = new javax.swing.JButton();
        paginaFiltro = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        BotaoLupa = new javax.swing.JButton();
        SlcArea = new javax.swing.JComboBox<>();
        SlcHora = new javax.swing.JComboBox<>();
        SlcValor = new javax.swing.JComboBox<>();
        BotaoVoltar = new javax.swing.JButton();
        TitleFiltro = new javax.swing.JLabel();
        IntrFiltro = new javax.swing.JLabel();
        IDFiltro = new javax.swing.JTextField();
        VisualFiltro = new javax.swing.JButton();
        paginaAdm = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        BotaoAdc = new javax.swing.JButton();
        BotaoEditar = new javax.swing.JButton();
        BotaoRmv = new javax.swing.JButton();
        BotaoVoltarAdm = new javax.swing.JButton();
        TitleAdm = new javax.swing.JLabel();
        paginaAdc = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        TitleAdc = new javax.swing.JLabel();
        TitleNome = new javax.swing.JLabel();
        NomeVg = new javax.swing.JTextField();
        TitleArea = new javax.swing.JLabel();
        AreaCad = new javax.swing.JComboBox<>();
        TitleSal = new javax.swing.JLabel();
        SalarioCad = new javax.swing.JTextField();
        TitleHora = new javax.swing.JLabel();
        HorarioCad = new javax.swing.JComboBox<>();
        BotaoCancel = new javax.swing.JButton();
        BotaoCadastra = new javax.swing.JButton();
        TitleEmpresa = new javax.swing.JLabel();
        NomeEmpresa = new javax.swing.JTextField();
        paginaRemove = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ExibeRmv = new javax.swing.JTextArea();
        BotaoLupaRmv = new javax.swing.JButton();
        SlcAreaRmv = new javax.swing.JComboBox<>();
        SlcHoraRmv = new javax.swing.JComboBox<>();
        SlcValorRmv = new javax.swing.JComboBox<>();
        TitleRmv = new javax.swing.JLabel();
        IntrRmv = new javax.swing.JLabel();
        IDRmv = new javax.swing.JTextField();
        RemoveVg = new javax.swing.JButton();
        BotaoVoltarRmv = new javax.swing.JButton();
        paginaEdit = new javax.swing.JPanel();
        SlcAreaEdit = new javax.swing.JComboBox<>();
        SlcHoraEdit = new javax.swing.JComboBox<>();
        SlcValorEdit = new javax.swing.JComboBox<>();
        TitleEdit = new javax.swing.JLabel();
        IntrEdit = new javax.swing.JLabel();
        IDEdit = new javax.swing.JTextField();
        EditVg = new javax.swing.JButton();
        BotaoVoltarEdit = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        ExibeEdit = new javax.swing.JTextArea();
        BotaoLupaEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        painelPrincipal.setLayout(new java.awt.CardLayout());

        paginaPrincipal.setBackground(new java.awt.Color(255, 228, 196));
        paginaPrincipal.setPreferredSize(new java.awt.Dimension(700, 600));

        TitlePag.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TitlePag.setText("Bem vindo ao VagasExpress!");

        TodasVagas.setColumns(20);
        TodasVagas.setRows(5);
        AdcScroll.setViewportView(TodasVagas);

        BotaoFiltro.setBackground(new java.awt.Color(46, 139, 87));
        BotaoFiltro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoFiltro.setText("Filtro");
        BotaoFiltro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoFiltroActionPerformed(evt);
            }
        });

        BotaoAdm.setBackground(new java.awt.Color(46, 139, 87));
        BotaoAdm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoAdm.setText("Administrar");
        BotaoAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAdmActionPerformed(evt);
            }
        });

        BotaoSair.setBackground(new java.awt.Color(255, 0, 0));
        BotaoSair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoSair.setText("Sair");
        BotaoSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoSairActionPerformed(evt);
            }
        });

        IntrPrinc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IntrPrinc.setText("Digite o ID da vaga:");

        VisualVg.setBackground(new java.awt.Color(60, 179, 113));
        VisualVg.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Área de Trabalho\\Docs_2_Semestre\\loupe.png")); // NOI18N

        javax.swing.GroupLayout paginaPrincipalLayout = new javax.swing.GroupLayout(paginaPrincipal);
        paginaPrincipal.setLayout(paginaPrincipalLayout);
        paginaPrincipalLayout.setHorizontalGroup(
            paginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaPrincipalLayout.createSequentialGroup()
                .addGroup(paginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paginaPrincipalLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(paginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TitlePag)
                            .addComponent(AdcScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paginaPrincipalLayout.createSequentialGroup()
                                .addComponent(IntrPrinc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IDPrinc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(VisualVg, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(paginaPrincipalLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(BotaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
            .addGroup(paginaPrincipalLayout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(BotaoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BotaoAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(80, 80, 80))
        );
        paginaPrincipalLayout.setVerticalGroup(
            paginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaPrincipalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitlePag)
                .addGap(18, 18, 18)
                .addComponent(AdcScroll, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(paginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IntrPrinc)
                    .addComponent(IDPrinc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VisualVg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(paginaPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(67, 67, 67)
                .addComponent(BotaoSair, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59))
        );

        painelPrincipal.add(paginaPrincipal, "card2");

        paginaFiltro.setBackground(new java.awt.Color(255, 228, 196));
        paginaFiltro.setPreferredSize(new java.awt.Dimension(700, 600));

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jScrollPane5.setViewportView(jTextArea2);

        BotaoLupa.setText("jButton4");

        SlcArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        SlcHora.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SlcHora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlcHoraActionPerformed(evt);
            }
        });

        SlcValor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        BotaoVoltar.setBackground(new java.awt.Color(176, 224, 230));
        BotaoVoltar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoVoltar.setText("Voltar");
        BotaoVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarActionPerformed(evt);
            }
        });

        TitleFiltro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TitleFiltro.setText("Filtre entre as vagas disponíveis:");

        IntrFiltro.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IntrFiltro.setText("Digite o ID da vaga:");

        VisualFiltro.setBackground(new java.awt.Color(60, 179, 113));
        VisualFiltro.setIcon(new javax.swing.ImageIcon("C:\\Users\\gabri\\OneDrive\\Área de Trabalho\\Docs_2_Semestre\\search.png")); // NOI18N

        javax.swing.GroupLayout paginaFiltroLayout = new javax.swing.GroupLayout(paginaFiltro);
        paginaFiltro.setLayout(paginaFiltroLayout);
        paginaFiltroLayout.setHorizontalGroup(
            paginaFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaFiltroLayout.createSequentialGroup()
                .addGroup(paginaFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paginaFiltroLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(paginaFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TitleFiltro)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paginaFiltroLayout.createSequentialGroup()
                                .addComponent(BotaoLupa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SlcArea, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SlcHora, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SlcValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(paginaFiltroLayout.createSequentialGroup()
                                .addComponent(IntrFiltro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(IDFiltro)
                                .addGap(18, 18, 18)
                                .addComponent(VisualFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(paginaFiltroLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(BotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        paginaFiltroLayout.setVerticalGroup(
            paginaFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaFiltroLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(TitleFiltro)
                .addGap(35, 35, 35)
                .addGroup(paginaFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoLupa, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SlcArea, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SlcHora, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SlcValor, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paginaFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IntrFiltro)
                    .addComponent(IDFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VisualFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(BotaoVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        painelPrincipal.add(paginaFiltro, "card3");

        paginaAdm.setBackground(new java.awt.Color(255, 228, 196));
        paginaAdm.setPreferredSize(new java.awt.Dimension(700, 600));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        BotaoAdc.setBackground(new java.awt.Color(46, 139, 87));
        BotaoAdc.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoAdc.setText("Adicionar");
        BotaoAdc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoAdcActionPerformed(evt);
            }
        });

        BotaoEditar.setBackground(new java.awt.Color(64, 224, 208));
        BotaoEditar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoEditar.setText("Editar");
        BotaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoEditarActionPerformed(evt);
            }
        });

        BotaoRmv.setBackground(new java.awt.Color(255, 0, 0));
        BotaoRmv.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoRmv.setText("Remover");
        BotaoRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoRmvActionPerformed(evt);
            }
        });

        BotaoVoltarAdm.setBackground(new java.awt.Color(176, 224, 230));
        BotaoVoltarAdm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BotaoVoltarAdm.setText("Voltar");
        BotaoVoltarAdm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarAdmActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BotaoAdc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoRmv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BotaoVoltarAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(150, 150, 150))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(BotaoAdc, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(BotaoEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(BotaoRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addComponent(BotaoVoltarAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        TitleAdm.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TitleAdm.setText("Bem vindo a central de cadastro!");

        javax.swing.GroupLayout paginaAdmLayout = new javax.swing.GroupLayout(paginaAdm);
        paginaAdm.setLayout(paginaAdmLayout);
        paginaAdmLayout.setHorizontalGroup(
            paginaAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paginaAdmLayout.createSequentialGroup()
                .addContainerGap(139, Short.MAX_VALUE)
                .addGroup(paginaAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TitleAdm, javax.swing.GroupLayout.PREFERRED_SIZE, 329, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(133, 133, 133))
        );
        paginaAdmLayout.setVerticalGroup(
            paginaAdmLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paginaAdmLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(TitleAdm)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50))
        );

        painelPrincipal.add(paginaAdm, "card4");

        paginaAdc.setBackground(new java.awt.Color(255, 228, 196));
        paginaAdc.setPreferredSize(new java.awt.Dimension(700, 600));

        jPanel2.setBackground(new java.awt.Color(255, 228, 196));
        jPanel2.setPreferredSize(new java.awt.Dimension(700, 600));

        TitleAdc.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        TitleAdc.setText("Adicione as informações:");

        TitleNome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TitleNome.setText("Nome :");

        NomeVg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeVgActionPerformed(evt);
            }
        });

        TitleArea.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TitleArea.setText("Area :");

        AreaCad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computação", "Direito", "Administração", "Mecânica" }));
        AreaCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AreaCadActionPerformed(evt);
            }
        });

        TitleSal.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TitleSal.setText("Salario :");

        SalarioCad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalarioCadActionPerformed(evt);
            }
        });

        TitleHora.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TitleHora.setText("Horário :");

        HorarioCad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manhã", "Tarde", "Noite" }));

        BotaoCancel.setBackground(new java.awt.Color(255, 0, 0));
        BotaoCancel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotaoCancel.setText("Cancelar");
        BotaoCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelActionPerformed(evt);
            }
        });

        BotaoCadastra.setBackground(new java.awt.Color(60, 179, 113));
        BotaoCadastra.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotaoCadastra.setText("Cadastrar");
        BotaoCadastra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastraActionPerformed(evt);
            }
        });

        TitleEmpresa.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        TitleEmpresa.setText("Empresa :");

        NomeEmpresa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NomeEmpresaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addComponent(TitleAdc))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TitleSal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SalarioCad, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TitleNome)
                                    .addComponent(TitleArea))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(NomeVg)
                                    .addComponent(AreaCad, 0, 393, Short.MAX_VALUE)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TitleHora)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HorarioCad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(TitleEmpresa)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NomeEmpresa))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(180, 180, 180)
                        .addComponent(BotaoCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100)
                        .addComponent(BotaoCadastra, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(120, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TitleAdc)
                .addGap(87, 87, 87)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleNome)
                    .addComponent(NomeVg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleEmpresa)
                    .addComponent(NomeEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleArea)
                    .addComponent(AreaCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleSal)
                    .addComponent(SalarioCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TitleHora)
                    .addComponent(HorarioCad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotaoCadastra, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paginaAdcLayout = new javax.swing.GroupLayout(paginaAdc);
        paginaAdc.setLayout(paginaAdcLayout);
        paginaAdcLayout.setHorizontalGroup(
            paginaAdcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaAdcLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        paginaAdcLayout.setVerticalGroup(
            paginaAdcLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaAdcLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        painelPrincipal.add(paginaAdc, "card5");

        paginaRemove.setPreferredSize(new java.awt.Dimension(700, 600));

        jPanel3.setBackground(new java.awt.Color(255, 228, 196));

        ExibeRmv.setColumns(20);
        ExibeRmv.setRows(5);
        jScrollPane6.setViewportView(ExibeRmv);

        BotaoLupaRmv.setText("jButton4");

        SlcAreaRmv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        SlcHoraRmv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SlcHoraRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlcHoraRmvActionPerformed(evt);
            }
        });

        SlcValorRmv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        TitleRmv.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TitleRmv.setText("Filtre entre as vagas disponíveis:");

        IntrRmv.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IntrRmv.setText("Digite o ID da vaga:");

        RemoveVg.setBackground(new java.awt.Color(255, 0, 0));
        RemoveVg.setText("jButton1");

        BotaoVoltarRmv.setBackground(new java.awt.Color(176, 224, 230));
        BotaoVoltarRmv.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotaoVoltarRmv.setText("Voltar");
        BotaoVoltarRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarRmvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TitleRmv)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(BotaoLupaRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SlcAreaRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SlcHoraRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SlcValorRmv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(IntrRmv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDRmv)
                        .addGap(18, 18, 18)
                        .addComponent(RemoveVg, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(BotaoVoltarRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TitleRmv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoLupaRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SlcAreaRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SlcHoraRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SlcValorRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IntrRmv)
                    .addComponent(IDRmv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RemoveVg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(BotaoVoltarRmv, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        javax.swing.GroupLayout paginaRemoveLayout = new javax.swing.GroupLayout(paginaRemove);
        paginaRemove.setLayout(paginaRemoveLayout);
        paginaRemoveLayout.setHorizontalGroup(
            paginaRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaRemoveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        paginaRemoveLayout.setVerticalGroup(
            paginaRemoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaRemoveLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        painelPrincipal.add(paginaRemove, "card6");

        paginaEdit.setBackground(new java.awt.Color(255, 228, 196));
        paginaEdit.setPreferredSize(new java.awt.Dimension(700, 600));

        SlcAreaEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        SlcHoraEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        SlcHoraEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SlcHoraEditActionPerformed(evt);
            }
        });

        SlcValorEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        TitleEdit.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TitleEdit.setText("Filtre entre as vagas disponíveis:");

        IntrEdit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        IntrEdit.setText("Digite o ID da vaga:");

        EditVg.setBackground(new java.awt.Color(60, 179, 113));
        EditVg.setText("jButton1");

        BotaoVoltarEdit.setBackground(new java.awt.Color(176, 224, 230));
        BotaoVoltarEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        BotaoVoltarEdit.setText("Voltar");
        BotaoVoltarEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoVoltarEditActionPerformed(evt);
            }
        });

        ExibeEdit.setColumns(20);
        ExibeEdit.setRows(5);
        jScrollPane7.setViewportView(ExibeEdit);

        BotaoLupaEdit.setText("jButton4");

        javax.swing.GroupLayout paginaEditLayout = new javax.swing.GroupLayout(paginaEdit);
        paginaEdit.setLayout(paginaEditLayout);
        paginaEditLayout.setHorizontalGroup(
            paginaEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaEditLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(paginaEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(paginaEditLayout.createSequentialGroup()
                        .addGroup(paginaEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TitleEdit)
                            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(paginaEditLayout.createSequentialGroup()
                                .addComponent(BotaoLupaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SlcAreaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SlcHoraEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(SlcValorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(34, Short.MAX_VALUE))
                    .addGroup(paginaEditLayout.createSequentialGroup()
                        .addComponent(IntrEdit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(IDEdit)
                        .addGap(18, 18, 18)
                        .addComponent(EditVg, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(146, 146, 146))))
            .addGroup(paginaEditLayout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(BotaoVoltarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        paginaEditLayout.setVerticalGroup(
            paginaEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paginaEditLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(TitleEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paginaEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoLupaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SlcAreaEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SlcHoraEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SlcValorEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(paginaEditLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IntrEdit)
                    .addComponent(IDEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EditVg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(BotaoVoltarEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        painelPrincipal.add(paginaEdit, "card7");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>                        

    private void BotaoFiltroActionPerformed(java.awt.event.ActionEvent evt) {                                            
        CardLayout troca = (CardLayout) painelPrincipal.getLayout(); // Vai da pg Principal para a pg de Filtro
        troca.show(painelPrincipal, "card3");
    }                                           

    private void BotaoSairActionPerformed(java.awt.event.ActionEvent evt) {                                          
        System.exit(0);
    }                                         

    private void SlcHoraActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void BotaoVoltarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        CardLayout troca = (CardLayout) painelPrincipal.getLayout(); // Vai da pg de Filtro para a pg Principal
        troca.show(painelPrincipal, "card2");
    }                                           

    private void BotaoEditarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        CardLayout troca = (CardLayout) painelPrincipal.getLayout();
        troca.show(painelPrincipal, "card7");
    }                                           

    private void BotaoAdcActionPerformed(java.awt.event.ActionEvent evt) {                                         
        CardLayout troca = (CardLayout) painelPrincipal.getLayout();
        troca.show(painelPrincipal, "card5");
    }                                        

    private void BotaoRmvActionPerformed(java.awt.event.ActionEvent evt) {                                         
        CardLayout troca = (CardLayout) painelPrincipal.getLayout();
        troca.show(painelPrincipal, "card6");
    }                                        

    private void BotaoVoltarAdmActionPerformed(java.awt.event.ActionEvent evt) {                                               
        CardLayout troca = (CardLayout) painelPrincipal.getLayout(); // Vai da pg de Adm para a pg Principal
        troca.show(painelPrincipal, "card2");
    }                                              

    private void BotaoAdmActionPerformed(java.awt.event.ActionEvent evt) {                                         
        controle.verificaSenha();
    }                                        

    private void NomeVgActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void AreaCadActionPerformed(java.awt.event.ActionEvent evt) {                                        
        // TODO add your handling code here:
    }                                       

    private void SalarioCadActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void BotaoCancelActionPerformed(java.awt.event.ActionEvent evt) {                                            
        CardLayout troca = (CardLayout) painelPrincipal.getLayout();
        troca.show(painelPrincipal, "card4");
    }                                           

    private void SlcHoraRmvActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void BotaoVoltarRmvActionPerformed(java.awt.event.ActionEvent evt) {                                               
        CardLayout troca = (CardLayout) painelPrincipal.getLayout();
        troca.show(painelPrincipal, "card4");
    }                                              

    private void SlcHoraEditActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void BotaoVoltarEditActionPerformed(java.awt.event.ActionEvent evt) {                                                
        CardLayout troca = (CardLayout) painelPrincipal.getLayout();
        troca.show(painelPrincipal, "card4");
    }                                               

    private void NomeEmpresaActionPerformed(java.awt.event.ActionEvent evt) {                                            
        // TODO add your handling code here:
    }                                           

    private void BotaoCadastraActionPerformed(java.awt.event.ActionEvent evt) {                                              
        String nome = NomeVg.getText();
        String empresa = NomeEmpresa.getText();
        String area = (String) AreaCad.getSelectedItem();
        String salario = SalarioCad.getText();
        String horario = (String) HorarioCad.getSelectedItem();
        if (nome.isEmpty() || empresa.isEmpty() || salario.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Por favor, preencha todos os campos.");
        } else {
            controle.cadastrarVaga(nome, empresa, area, salario, horario);
            JOptionPane.showMessageDialog(this, "Vaga cadastrada com sucesso!");

            //Limpa os textField após pegar a informação
            NomeVg.setText("");
            NomeEmpresa.setText("");
            SalarioCad.setText("");

            CardLayout troca = (CardLayout) painelPrincipal.getLayout();
            troca.show(painelPrincipal, "card4");
        }
    }                                             

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PaginaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PaginaInicial().setVisible(true);
            }
        });
    }

    Principal controle;
    // Variables declaration - do not modify                     
    private javax.swing.JScrollPane AdcScroll;
    private javax.swing.JComboBox<String> AreaCad;
    private javax.swing.JButton BotaoAdc;
    private javax.swing.JButton BotaoAdm;
    private javax.swing.JButton BotaoCadastra;
    private javax.swing.JButton BotaoCancel;
    private javax.swing.JButton BotaoEditar;
    private javax.swing.JButton BotaoFiltro;
    private javax.swing.JButton BotaoLupa;
    private javax.swing.JButton BotaoLupaEdit;
    private javax.swing.JButton BotaoLupaRmv;
    private javax.swing.JButton BotaoRmv;
    private javax.swing.JButton BotaoSair;
    private javax.swing.JButton BotaoVoltar;
    private javax.swing.JButton BotaoVoltarAdm;
    private javax.swing.JButton BotaoVoltarEdit;
    private javax.swing.JButton BotaoVoltarRmv;
    private javax.swing.JButton EditVg;
    private javax.swing.JTextArea ExibeEdit;
    private javax.swing.JTextArea ExibeRmv;
    private javax.swing.JComboBox<String> HorarioCad;
    private javax.swing.JTextField IDEdit;
    private javax.swing.JTextField IDFiltro;
    private javax.swing.JTextField IDPrinc;
    private javax.swing.JTextField IDRmv;
    private javax.swing.JLabel IntrEdit;
    private javax.swing.JLabel IntrFiltro;
    private javax.swing.JLabel IntrPrinc;
    private javax.swing.JLabel IntrRmv;
    private javax.swing.JTextField NomeEmpresa;
    private javax.swing.JTextField NomeVg;
    private javax.swing.JButton RemoveVg;
    private javax.swing.JTextField SalarioCad;
    private javax.swing.JComboBox<String> SlcArea;
    private javax.swing.JComboBox<String> SlcAreaEdit;
    private javax.swing.JComboBox<String> SlcAreaRmv;
    private javax.swing.JComboBox<String> SlcHora;
    private javax.swing.JComboBox<String> SlcHoraEdit;
    private javax.swing.JComboBox<String> SlcHoraRmv;
    private javax.swing.JComboBox<String> SlcValor;
    private javax.swing.JComboBox<String> SlcValorEdit;
    private javax.swing.JComboBox<String> SlcValorRmv;
    private javax.swing.JLabel TitleAdc;
    private javax.swing.JLabel TitleAdm;
    private javax.swing.JLabel TitleArea;
    private javax.swing.JLabel TitleEdit;
    private javax.swing.JLabel TitleEmpresa;
    private javax.swing.JLabel TitleFiltro;
    private javax.swing.JLabel TitleHora;
    private javax.swing.JLabel TitleNome;
    private javax.swing.JLabel TitlePag;
    private javax.swing.JLabel TitleRmv;
    private javax.swing.JLabel TitleSal;
    private javax.swing.JTextArea TodasVagas;
    private javax.swing.JButton VisualFiltro;
    private javax.swing.JButton VisualVg;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JPanel paginaAdc;
    private javax.swing.JPanel paginaAdm;
    private javax.swing.JPanel paginaEdit;
    private javax.swing.JPanel paginaFiltro;
    private javax.swing.JPanel paginaPrincipal;
    private javax.swing.JPanel paginaRemove;
    private javax.swing.JPanel painelPrincipal;
    // End of variables declaration                   
}
